// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const placeholder = `-- name: Placeholder :many
SELECT boo from foo
`

func (q *Queries) Placeholder(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, placeholder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.N