
// Code generated by sqlc-pg-gen. DO NOT EDIT.

package postgresql

import (
	"github.com/kyleconroy/sqlc/internal/sql/ast"
	"github.com/kyleconroy/sqlc/internal/sql/catalog"
)

var funcsgenInformationSchema = []*catalog.Function{}

func genInformationSchema() *catalog.Schema {
	s := &catalog.Schema{Name: "information_schema"}
	s.Funcs = funcsgenInformationSchema
	s.Tables = []*catalog.Table{
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "_pg_foreign_data_wrappers",
			},
			Columns: []*catalog.Column{
				{
					Name:   "oid",
					Type:   ast.TypeName{Name: "oid"},
					Length: toPointer(4),
				},
				{
					Name:   "fdwowner",
					Type:   ast.TypeName{Name: "oid"},
					Length: toPointer(4),
				},
				{
					Name:    "fdwoptions",
					Type:    ast.TypeName{Name: "_text"},
					IsArray: true,
				},
				{
					Name:   "foreign_data_wrapper_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_data_wrapper_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "authorization_identifier",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name: "foreign_data_wrapper_language",
					Type: ast.TypeName{Name: "character_data"},
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "_pg_foreign_servers",
			},
			Columns: []*catalog.Column{
				{
					Name:   "oid",
					Type:   ast.TypeName{Name: "oid"},
					Length: toPointer(4),
				},
				{
					Name:    "srvoptions",
					Type:    ast.TypeName{Name: "_text"},
					IsArray: true,
				},
				{
					Name:   "foreign_server_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_server_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_data_wrapper_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_data_wrapper_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name: "foreign_server_type",
					Type: ast.TypeName{Name: "character_data"},
				},
				{
					Name: "foreign_server_version",
					Type: ast.TypeName{Name: "character_data"},
				},
				{
					Name:   "authorization_identifier",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "_pg_foreign_table_columns",
			},
			Columns: []*catalog.Column{
				{
					Name:   "nspname",
					Type:   ast.TypeName{Name: "name"},
					Length: toPointer(64),
				},
				{
					Name:   "relname",
					Type:   ast.TypeName{Name: "name"},
					Length: toPointer(64),
				},
				{
					Name:   "attname",
					Type:   ast.TypeName{Name: "name"},
					Length: toPointer(64),
				},
				{
					Name:    "attfdwoptions",
					Type:    ast.TypeName{Name: "_text"},
					IsArray: true,
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "_pg_foreign_tables",
			},
			Columns: []*catalog.Column{
				{
					Name:   "foreign_table_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_table_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_table_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:    "ftoptions",
					Type:    ast.TypeName{Name: "_text"},
					IsArray: true,
				},
				{
					Name:   "foreign_server_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_server_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "authorization_identifier",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "_pg_user_mappings",
			},
			Columns: []*catalog.Column{
				{
					Name:   "oid",
					Type:   ast.TypeName{Name: "oid"},
					Length: toPointer(4),
				},
				{
					Name:    "umoptions",
					Type:    ast.TypeName{Name: "_text"},
					IsArray: true,
				},
				{
					Name:   "umuser",
					Type:   ast.TypeName{Name: "oid"},
					Length: toPointer(4),
				},
				{
					Name:   "authorization_identifier",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_server_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "foreign_server_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "srvowner",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "administrable_role_authorizations",
			},
			Columns: []*catalog.Column{
				{
					Name:   "grantee",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "role_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name: "is_grantable",
					Type: ast.TypeName{Name: "yes_or_no"},
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "applicable_roles",
			},
			Columns: []*catalog.Column{
				{
					Name:   "grantee",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "role_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name: "is_grantable",
					Type: ast.TypeName{Name: "yes_or_no"},
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "attributes",
			},
			Columns: []*catalog.Column{
				{
					Name:   "udt_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "udt_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "udt_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "attribute_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "ordinal_position",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name: "attribute_default",
					Type: ast.TypeName{Name: "character_data"},
				},
				{
					Name: "is_nullable",
					Type: ast.TypeName{Name: "yes_or_no"},
				},
				{
					Name: "data_type",
					Type: ast.TypeName{Name: "character_data"},
				},
				{
					Name:   "character_maximum_length",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name:   "character_octet_length",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name:   "character_set_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_set_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_set_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "collation_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "collation_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "collation_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "numeric_precision",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name:   "numeric_precision_radix",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name:   "numeric_scale",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name:   "datetime_precision",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name: "interval_type",
					Type: ast.TypeName{Name: "character_data"},
				},
				{
					Name:   "interval_precision",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name:   "attribute_udt_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "attribute_udt_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "attribute_udt_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "scope_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "scope_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "scope_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "maximum_cardinality",
					Type:   ast.TypeName{Name: "cardinal_number"},
					Length: toPointer(4),
				},
				{
					Name:   "dtd_identifier",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name: "is_derived_reference_attribute",
					Type: ast.TypeName{Name: "yes_or_no"},
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "character_sets",
			},
			Columns: []*catalog.Column{
				{
					Name:   "character_set_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_set_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_set_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_repertoire",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "form_of_use",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "default_collate_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "default_collate_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "default_collate_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "check_constraint_routine_usage",
			},
			Columns: []*catalog.Column{
				{
					Name:   "constraint_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "constraint_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "constraint_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "specific_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "specific_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "specific_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "check_constraints",
			},
			Columns: []*catalog.Column{
				{
					Name:   "constraint_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "constraint_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "constraint_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name: "check_clause",
					Type: ast.TypeName{Name: "character_data"},
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "collation_character_set_applicability",
			},
			Columns: []*catalog.Column{
				{
					Name:   "collation_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "collation_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "collation_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_set_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_set_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "character_set_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "collations",
			},
			Columns: []*catalog.Column{
				{
					Name:   "collation_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "collation_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "collation_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name: "pad_attribute",
					Type: ast.TypeName{Name: "character_data"},
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "column_column_usage",
			},
			Columns: []*catalog.Column{
				{
					Name:   "table_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "table_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "table_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "column_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "dependent_column",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "column_domain_usage",
			},
			Columns: []*catalog.Column{
				{
					Name:   "domain_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "domain_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "domain_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "table_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "table_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "table_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "column_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
			},
		},
		{
			Rel: &ast.TableName{
				Catalog: "pg_catalog",
				Schema:  "information_schema",
				Name:    "column_options",
			},
			Columns: []*catalog.Column{
				{
					Name:   "table_catalog",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "table_schema",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},
				{
					Name:   "table_name",
					Type:   ast.TypeName{Name: "sql_identifier"},
					Length: toPointer(64),
				},