// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"
)

const twoJoins = `-- name: TwoJoins :many
SELECT foo.bar_id, foo.baz_id
FROM foo
JOIN bar ON bar.id = bar_id
JOIN baz ON baz.id = baz_id
`

func (q *Queries) TwoJoins(ctx cont