// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const fooByBarB = `-- name: FooByBarB :many
SELECT a, b from foo where foo.a in (select 