// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"
)

const listBar = `-- name: ListBar :many
SELECT id FROM bar
`

func (q *Queries) ListBar(ctx context.Context) ([]int32, error) {
	rows, err := q.db