name: Feature Request
description: Request a new feature or a change to an existing feature
labels: [enhancement, triage]
body:
  - type: textarea
    id: feature
    attributes:
      label: What do you want to change?
      placeholder: Tell us what you want
      value: "Free unicorns!"
    validations:
      required: true
  - type: dropdown
    id: engines
    a