
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package datatype

import (
	"database/sql"
	"time"

	"github.com/tabbed/pqtype"
)

type DtCharacter struct {
	A sql.NullString
	B sql.NullString
	C sql.NullString
	D sql.NullString
	E sql.NullString
}

type DtCharacterNotNull struct {
	A string
	B string
	C string
	D string
	E string
}