// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const starExpansionJoin = `-- name: StarExpansionJoin :many
SELECT a, b, c, d FROM foo, bar
`

type StarExpansionJoinRow struct {
	A pgtype.Text
	B pgtype.Text
	C pgtype.Text
	D pgtype.Text
}

func (q *Queries) StarExpansionJoin(ctx context.Context) ([]StarExpansionJoinRow, error) {
	rows, err := q.db.Query(ctx, starExpansionJoin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var item