// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/kyleconroy/sqlc/internal/sql/ast"
	"github.com/kyleconroy/sqlc/internal/sql/catalog"
)

var funcsCitext = []*catalog.Function{
	{
		Name: "citext",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeNa