// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/kyleconroy/sqlc/internal/sql/ast"
	"github.com/kyleconroy/sqlc/internal/sql/catalog"
)

var funcsHstore = []*catalog.Function{
	{
		Name: "akeys",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "hstore"},
			},
		},
		ReturnType: &ast.TypeName{Name: "text[]"},
	},
	{
		Name: "avals",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "hstore"},
			},
		},
		ReturnType: &ast.TypeName{Name: "text[]"},
	},
	{
		Name: "defined",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "hstore"},
			},
			{
				Type: &ast.TypeName{Name: "text"},
			},
		},
		ReturnType: &ast.TypeName{Name: "boolean"},
	},
	{
		Name: "delete",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "hstore"},
			},
			{
				Type: &ast.TypeName{Name: "hstore"},
			},
		},
		ReturnType: &ast.TypeName{Name: "hstore"},
	},
	{
		Name: "delete",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "hstore"},
			},