// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/kyleconroy/sqlc/internal/sql/ast"
	"github.com/kyleconroy/sqlc/internal/sql/catalog"
)

var funcsIsn = []*catalog.Function{
	{
		Name: "btean13cmp",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "ean13"},
			},
			{
				Type: &ast.TypeName{Name: "ean13"},
			},
		},
		ReturnType: &ast.TypeName{Name: "integer"},
	},
	{
		Name: "btean13cmp",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "ean13"},
			},
			{
				Type: &ast.TypeName{Name: "isbn"},
			},
		},
		ReturnType: &ast.TypeName{Name: "integer"},
	},
	{
		Name: "btean13cmp",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "ean13"},
			},
			{
				Type: &ast.TypeName{Name: "isbn13"},
			},
		},
		ReturnType: &ast.TypeName{Name: "integer"},
	},
	{
		Name: "btean13cmp",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "ean13"},
			},
			{
				Type: &ast.TypeName{Name: "ismn"},
			},
		},
		ReturnType: &ast.TypeName{Name: "integer"},
	},
	{
		Name: "btean13cmp",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "ean13"},
			},
			{
				Type: &ast.TypeName{Name: "ismn13"},
			},
		},
		ReturnType: &ast.TypeName{Name: "integer"},
	},
	{
		Name: "btean13cmp",
		Args: []*catalog.Argument{
			{
				Type: &ast.TypeName{Name: "ean13"},
			},
			{
				Type: &ast.TypeName{Name: "issn"},
			},
		},
		Return