// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/kyleconroy/sqlc/internal/sql/ast"
	"github.com/kyleconroy/sqlc/internal/sql/catalog"
)

var funcsPgStatStatements = []*catalog.Function{
	{
		Name: "pg_stat_statements",
		Args: []*catalog.Argument{
			{
				Name: 