// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"
)

const any = `-- name: Any :many
SELECT id
FROM bar
WHERE foo = ANY($1: