// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"
)

const math = `-- name: Math :many
SELECT num, num / 1024 as division FROM foo
`

type MathRow struct {
	Num      int32
	Division int32
}

func (q *Queries) Math(ctx context.Co