// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package querytest

import (
	"context"
)

const listCalories = `-- name: ListCalories :many
SELECT id FROM calories
`

func (q *Queries) ListCalories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCalories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
