// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package date_and_time_functions

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...i